spring:
  application:
    name: loja-rest

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath:db/migration,classpath:db/testdata

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123

rabbitmq:
  exchange:
    name: loja_exchange
  queue:
    product:
      name: loja_product
    tag:
      name: loja_tag
  routingKey:
    product:
      name: loja_routing_key_product
    tag:
      name: loja_routing_key_tag