services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    networks:
      - rabbitmq_go_net
    restart: always

  cache:
    image: redis:7.2.1-alpine
    container_name: 'redis'
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redis123
    volumes:
      - cache:/data

  loja-log:
    container_name: 'loja-log'
    build:
      context: ./loja-log/
      dockerfile: Dockerfile
    image: loja-log:latest
    depends_on:
      - rabbitmq
    network_mode: "host"

  loja-rest:
    container_name: 'loja-rest'
    build:
      context: ./loja-rest/
      dockerfile: Dockerfile
    image: loja-rest:latest
    ports:
      - 8080:8080
    depends_on:
      - rabbitmq
      - cache
    network_mode: "host"

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  cache:
    driver: local