version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=admin
        - RABBITMQ_DEFAULT_PASS=admin123
    restart: always
    networks:
        - rabbitmq_go_net

  loja-log:
    container_name: 'loja-log'
    build:
      context: ./loja-log/
      dockerfile: Dockerfile
    image: loja-log:latest

  loja-rest:
    container_name: 'loja-rest'
    build:
      context: ./loja-rest/
      dockerfile: Dockerfile
    image: loja-rest:latest
    ports:
      - 8080:8080

networks:
  rabbitmq_go_net:
    driver: bridge
